### ISSUE TITLE
Agregar Rol de Scrum Master | ISPC

### ISSUE THREAD

**Issue by Cristian-Sosa** [Cristian-Sosa/Git-Github-ISPC#1]
# Agregar roles en ConceptosScrum| ISPC

> Como Scrum Master quiero poder ver el rol de Scrum Master de la metodología Scrum

Criterios de aceptación:
- [ ] Buena ortografía
- [ ] Titulo del rol
- [ ] Descripción del rol
- [ ] Responsabilidades del rol

**Comment by Cristian-Sosa** [comment]
Pablo, en vez de usar una lista ordenada, para las responsabilidades, podrías colocar una desordenada para seguir con la coherencia. También asegurate de darle el "check" a las tareas dentro del Issue (para reconocer falcilmente si todo está realizado)

**Comment by Pablo1500** [comment]
okas
