### ISSUE TITLE
Agregar Ceremonia Sprint Planning | ISPC

### ISSUE THREAD

**Issue by Cristian-Sosa** [Cristian-Sosa/Git-Github-ISPC#5]
# Agregar ceremonia en ConceptosScrum| ISPC

> Como Scrum Master quiero poder ver la ceremonia Sprint Planning de la metodología Scrum

Criterios de aceptación:
- [x] Buena ortografía
- [x] Titulo de la ceremonia
- [x] Descripción de la ceremonia
- [x] Cuando se realiza
- [x] Duración de la ceremonia
- [x] Qué se obtiene
- [ ] Ejemplo breve

**Comment by pauamyc** [comment]
El Sprint Planning Meeting es una reunión de planificación. Se produce al iniciar cada Sprint y tiene por objetivo decidir qué se va  a realizar en el Sprint. Consiste en dos segmentos. 
Segmento 1:
- El Product Owner presenta el Backlog de producto con más alta prioridad.
- El equipo selecciona los ítems del Backlog de producto  con los que se puedan comprometer.

Segmento 2:
- Decidir la estrategia para alcanzar el objetivo del sprint (diseño).
- Las tareas son creadas.
- Se estiman las tareas y el Backlog de sprint.
- Colaborar todo el equipo, no solo el Scrum Master.
